-- ============================================================================
-- Trading Bot — Supabase / PostgreSQL schema
-- ============================================================================
-- Run this once in the Supabase SQL Editor (or psql) to create the table the
-- bot reads from and writes to. The bot talks to this table through the
-- Supabase REST API (PostgREST) at:  <SUPABASE_URL>/rest/v1/trades
--
-- Columns below match EXACTLY what step3_order_manager.py sends on the wire.
-- Prices / quantities / P&L are JSON numbers (the bot rounds to 8 dp), so they
-- are numeric columns here — NOT text.
-- ============================================================================

create table if not exists public.trades (
    id            bigint generated by default as identity primary key,

    -- ── identity / timing ──────────────────────────────────────────────────
    open_time     text             not null,   -- 'YYYY-MM-DD HH:MM UTC' (set on open)
    close_time    text,                         -- null while the position is open
    symbol        text             not null,   -- e.g. 'BTCUSDT'
    strategy      text             not null,   -- strategy id, e.g. 'S2_FVG_RETEST'
                                                --   (free text — holds any of the 5 strategy ids)
    direction     text             not null,   -- 'LONG' | 'SHORT'

    -- ── prices (numbers, rounded to 8 dp by the bot) ───────────────────────
    signal_price  double precision,            -- intended price from the signal
    entry_price   double precision,            -- actual fill price
    sl_price      double precision,            -- stop-loss price (rewritten in place when Lock-Profit arms)
    tp_price      double precision,            -- take-profit price
    quantity      double precision,            -- position size in the base asset

    -- ── sizing ─────────────────────────────────────────────────────────────
    margin_usdt   double precision,            -- margin committed (USDT)
    leverage      integer,                      -- effective leverage actually used

    -- ── outcome / P&L ──────────────────────────────────────────────────────
    outcome       text             not null,   -- 'OPEN' | 'WIN' | 'LP_WIN' | 'LOSS' | 'MANUAL_CLOSE'
    pnl_pct       double precision,            -- % P&L  (null while open)
    pnl_usdt      double precision,            -- USDT P&L (null while open)
    fee_usdt      double precision,            -- round-trip fee estimate
    slippage_pct  double precision,            -- fill vs signal price, %

    signal_time   text,                         -- 'YYYY-MM-DD HH:MM UTC' of the signal candle

    -- ── reserved ───────────────────────────────────────────────────────────
    oco_list_id   text,                         -- not written by the current bot; kept for compatibility

    created_at    timestamptz      default now()
);

-- Cheap, useful filters for the dashboard (5 strategies × multiple symbols).
create index if not exists trades_strategy_idx  on public.trades (strategy);
create index if not exists trades_symbol_idx    on public.trades (symbol);
create index if not exists trades_outcome_idx   on public.trades (outcome);
create index if not exists trades_open_time_idx on public.trades (open_time);


-- ============================================================================
-- ACCESS / API KEY  — read this before picking which Supabase key to use
-- ============================================================================
-- The bot is a trusted SERVER-SIDE backend (it never runs in a browser), so set
--   SUPABASE_KEY  in .env  ->  the *service_role* key
-- (Supabase dashboard -> Project Settings -> API -> service_role).
-- The service_role key bypasses Row-Level Security, so the table works
-- immediately with no extra policy setup. Keep it secret — it grants full DB
-- access and must NEVER be exposed publicly.
--
-- If you would rather use the *anon* key, RLS must be enabled WITH a policy or
-- every insert/select is rejected. In that case, uncomment the block below:
--
--   alter table public.trades enable row level security;
--   create policy "trades_full_access" on public.trades
--       for all using (true) with check (true);
--
-- (A blanket allow-all policy is fine for a private demo bot, but if the anon
--  key is ever shared publicly, anyone could read/modify this table.)
-- ============================================================================
